In [1]:
import numpy as np
ar = np.arange(2,51,3)
print(ar)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47 50]


In [2]:
import numpy as np
a1=[] 
a2=[]
for i in range(0, 5): 
    ele = int(input())
    a1.append(ele)
for i in range(0, 5): 
    ele = int(input())
    a2.append(ele) 
a1 = np.array(a1)
a2 = np.array(a2)
print(np.concatenate((a1,a2)))
print(np.sort(np.concatenate((a1,a2))))


2
3
6
8
9
0
1
3
4
5
[2 3 6 8 9 0 1 3 4 5]
[0 1 2 3 3 4 5 6 8 9]


In [3]:
import numpy as np
arr = np.array([[1,2,3],[1,3,5],[1,3,4]])
print(arr.ndim)
print(arr.size)

2
9


In [4]:
import numpy as np
arr=np.random.rand(5,)
print(arr.ndim)
nw_arr = arr[np.newaxis, :]
print(nw_arr.ndim)

1
2


In [5]:
import numpy as np
arr1=np.random.rand(3,3)
arr2=np.random.rand(3,3)
print(np.vstack((arr1,arr2)))
print() 
print(np.hstack((arr1,arr2)))

[[0.06997842 0.63203812 0.33867787]
 [0.79995197 0.16194012 0.10411539]
 [0.97781638 0.87305589 0.26807563]
 [0.56188933 0.14713829 0.60182735]
 [0.17777827 0.22712686 0.3185663 ]
 [0.98291053 0.54916617 0.0561114 ]]

[[0.06997842 0.63203812 0.33867787 0.56188933 0.14713829 0.60182735]
 [0.79995197 0.16194012 0.10411539 0.17777827 0.22712686 0.3185663 ]
 [0.97781638 0.87305589 0.26807563 0.98291053 0.54916617 0.0561114 ]]


In [7]:
import numpy as np
arr = np.array([1,9,3,1,5,2,5,9,4,3,9,7,6,2,9,2,6,7,8])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 7, 8, 9]), array([2, 3, 2, 1, 2, 2, 2, 1, 4], dtype=int64))
